apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-app
  namespace: health-core
spec:
  replicas: 2
  selector:
    matchLabels:
      app: core-app
  template:
    metadata:
      labels:
        app: core-app
    spec:
      containers:
        - name: core-app
          image: marcospls/health-core:latest
          ports:
            - containerPort: 5000
          # --- ADICIONE A PARTIR DAQUI ---
          env:
            - name: DB_HOST
              value: "health-flow-db.cacwd1w4zn8p.us-east-1.rds.amazonaws.com" # O endpoint do seu RDS
            - name: DB_NAME
              value: "healthflowdb"
            - name: DB_USER
              value: "dbadmin"
            - name: DB_PASS
              value: "Password123!"
          # --- FIM DA ADIÇÃO ---