apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: health-core
spec:
  selector:
    app: core
  ports:
  - protocol: TCP
    port: 80           # A porta que você acessa no navegador (Load Balancer)
    targetPort: 5000   # A porta onde o Python Flask está rodando dentro do Pod
  type: LoadBalancer   # MUDANÇA: Agora ele cria um IP externo na AWS