apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: health-core
spec:
  type: LoadBalancer
  selector:
    app: core-app # Deve ser igual ao label do seu deployment
  ports:
    - protocol: TCP
      port: 80         # Porta externa
      targetPort: 5000 # Porta interna do Flask