apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: health-core
spec:
  type: LoadBalancer
  selector:
    app: core-app
  ports:
    - protocol: TCP
      port: 80         # Porta que você digita no navegador (padrão)
      targetPort: 5000 # Porta que o seu app.py está ouvindo