apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: health-core
spec:
  type: ClusterIP  # Usamos ClusterIP + Port-Forward no Lab
  selector:
    app: core
  ports:
    - port: 80
      targetPort: 80