# Aplicação 1: O Core do HealthFlow
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: health-core-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/marcospls21/bootcamp-health-flow'  # <--- MUDE AQUI
    targetRevision: HEAD
    path: k8s/core
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: health-core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
# Aplicação 2: A Apresentação (Novo Vídeo/Index)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: health-apresentacao-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/marcospls21/bootcamp-health-flow' # <--- MUDE AQUI
    targetRevision: HEAD
    path: k8s/apresentacao
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: health-core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true