apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-app
  namespace: health-video
  labels:
    app: video
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video
  template:
    metadata:
      labels:
        app: video
    spec:
      containers:
      - name: video-app
        image: nginx:alpine # Usamos Nginx genérico só pra testar
        ports:
        - containerPort: 80