apiVersion: v1
kind: Service
metadata:
  name: video-app
  namespace: health-video  # Verifique se você realmente criou o namespace 'health-video' ou se vai usar 'health-core'
spec:
  selector:
    app: video-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer # MUDANÇA: Cria o IP externo