apiVersion: v1
kind: Service
metadata:
  name: video-service
  namespace: health-video
spec:
  type: LoadBalancer
  selector:
    app: video-app  # Deve bater com o label do Deployment acima
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80