name: üß® Terraform Destroy (Manual)

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'ATEN√á√ÉO: Digite "DESTROY" para confirmar a exclus√£o total:'
        required: true
        default: 'NO'

jobs:
  destroy-infra:
    name: üí£ Destroy Infrastructure
    runs-on: ubuntu-latest
    # Trava de seguran√ßa: O job s√≥ roda se voc√™ digitar DESTROY
    if: ${{ github.event.inputs.confirmation == 'DESTROY' }}
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        # O -upgrade garante que ele baixe as vers√µes corretas dos providers definidos no seu main.tf
        run: terraform init -upgrade

      - name: Terraform Destroy
        # O -auto-approve pula a pergunta de "yes/no" do terminal, j√° que voc√™ confirmou no input do GitHub
        run: terraform destroy -auto-approve